"""2.2 BUDGET — one number you can act on: what fraction of the window is spent before the
first user word.

Four inputs make up the cold-session context, and they are measured four different ways:

* `CLAUDE.md` — read whole, every session. Its per-section table is the reliable part of this
  check (docs/METHOD.md): the RATIO between sections survives any error in the byte-to-token
  estimator, because the same estimator is applied to every row.
* The ambient layer (`~/.claude`) — an on-disk CEILING, not a measured injection. Most of it
  (skills, commands) is loaded lazily, one line of description at a time, until a tool actually
  invokes it; this check can only weigh what is committed to the snapshot, and says so.
* `.mcp.json` — declares two MCP servers. Their tool schemas are generated by a running process
  bear-hug never starts (docs/CHARTER.md: bear-hug reads files, it does not run the subject's
  live servers), so this check measures the 200-byte declaration and reports the schema itself
  as UNMEASURABLE from a snapshot — the plan's own stated omission, confirmed rather than
  papered over.
* SessionStart / UserPromptSubmit `hook_inject` events, read from real transcripts via
  `replay.transcript`. This is the one number in this module that is not an estimate of
  anything: it is a byte count of traffic that actually happened.

METHOD HONESTY. `anthropic`'s tokenizer is permitted only in `evals/` (this file lives in
`lint/`, which CLAUDE.md's Engineering rule keeps stdlib-only), so every byte-to-token
conversion below uses a fixed heuristic, named in every finding it touches. The absolute token
totals this module reports are ESTIMATES. The byte counts, and the ratio between two rows
computed with the same estimator, are not.
"""

from __future__ import annotations

import json
import statistics
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from bearhug.lint.parse import parse_sections
from bearhug.model import Evidence, Finding, Severity
from bearhug.replay.transcript import Event, iter_events

# --- the estimator, named once and cited everywhere it is used -----------------------------

#: A commonly-cited English/code heuristic (~4 characters per token). Not calibrated against
#: this specific corpus — there is no ground truth to calibrate against without the real
#: tokenizer this module is forbidden to import. Treat every *_tokens number below as this
#: many significant figures: one.
BYTES_PER_TOKEN = 4.0

ESTIMATOR = (
    f"stdlib heuristic — {BYTES_PER_TOKEN:g} bytes/token (no real tokenizer: `anthropic` is "
    "evals-only per CLAUDE.md's Engineering rule, and this module lives in lint/)"
)

#: Named so the "what fraction of the window" number has a stated denominator. Context windows
#: vary by model and beta flag; this is documented as an assumption, not read from anywhere.
ASSUMED_CONTEXT_WINDOW_TOKENS = 200_000

LIMIT_ESTIMATE = (
    f"Uses {ESTIMATOR}. The absolute token count is an estimate and may be off by a large "
    "factor for dense code or non-English text. The RATIO between two rows computed with this "
    "same estimator is reliable regardless (docs/METHOD.md's Phase 2 token-budget caveat)."
)
LIMIT_REAL_TRAFFIC = (
    "Byte counts here are measured directly from `hook_additional_context` records in real "
    "transcripts, not estimated. Only the byte-to-token conversion is an estimate "
    f"({ESTIMATOR}). This is a correlational snapshot of one corpus window, not a claim about "
    "every future session — a harness change can move these numbers without this check running "
    "again."
)
LIMIT_UNMEASURABLE_MCP = (
    "`.mcp.json` names the servers; their tool schemas (name, description, JSON Schema per "
    "tool) exist only inside a running MCP server process. A filesystem snapshot cannot see "
    "them, and bear-hug will not start project-barracuda's live servers to find out "
    "(docs/CHARTER.md). This is the plan's own stated omission, confirmed here rather than "
    "silently repeated: 'measured 0 bytes' would read as 'costs nothing', which is not shown."
)
LIMIT_AMBIENT_CEILING = (
    "This is an on-disk CEILING: the byte size of every ambient file in the snapshot's manifest, "
    "not a measured injection. Most skill and command files are loaded lazily — one line of "
    "name+description in a session's skill inventory — until the Skill tool invokes them; only "
    "a file a hook `cat`s in full (confirmed for `using-superpowers/SKILL.md` by real SessionStart "
    "traffic, see the sessionstart-traffic finding) is known to be injected whole, every session."
)


def estimate_tokens(num_bytes: int) -> float:
    """Bytes to an estimated token count, using the one estimator this module is allowed."""
    return num_bytes / BYTES_PER_TOKEN


# --- CLAUDE.md, per section ------------------------------------------------------------------


@dataclass(slots=True)
class SectionBudget:
    id: str
    title: str
    num_bytes: int
    est_tokens: float
    fraction: float  # of the CLAUDE.md total, not of the context window


def claude_md_section_table(text: str) -> list[SectionBudget]:
    """Every numbered section, largest byte count first.

    A section's extent is its heading line through the line before the next heading (or EOF) —
    the same tiling `lint.parse.parse_sections` documents. Text before the first heading (a
    title, a one-line preamble) is real bytes too and is folded into the residual the caller
    computes from `total - sum(rows)`, rather than invented a home for it here.
    """
    sections = parse_sections(text)
    lines = text.splitlines()
    total = len(text.encode("utf-8")) or 1
    rows: list[SectionBudget] = []
    for section in sections:
        span = "\n".join(lines[section.line_start - 1 : section.line_end])
        num_bytes = len(span.encode("utf-8"))
        rows.append(
            SectionBudget(
                id=section.id,
                title=section.title,
                num_bytes=num_bytes,
                est_tokens=estimate_tokens(num_bytes),
                fraction=num_bytes / total,
            )
        )
    return sorted(rows, key=lambda r: -r.num_bytes)


# --- the ambient layer: an on-disk ceiling, not a measured injection ------------------------


@dataclass(slots=True)
class AmbientFile:
    path: str
    num_bytes: int


def ambient_footprint(manifest: dict[str, Any]) -> list[AmbientFile]:
    """Every file the snapshot captured under `~/.claude`, largest first."""
    files = manifest.get("layers", {}).get("ambient", {}).get("files", [])
    rows = [AmbientFile(path=f["path"], num_bytes=f["size"]) for f in files]
    return sorted(rows, key=lambda r: -r.num_bytes)


#: The plan's claim under test — see docs referenced in the BUDGET finding this backs.
SUPERPOWERS_SKILL_PATH = (
    "plugins/cache/superpowers-marketplace/superpowers/5.1.0/skills/using-superpowers/SKILL.md"
)


def check_superpowers_largest_claim(
    files: list[AmbientFile],
) -> tuple[bool, AmbientFile | None, AmbientFile | None]:
    """Is `using-superpowers/SKILL.md` the largest file in the ambient layer, by size?

    Returns (holds, superpowers_file, actual_largest). `files` is expected sorted largest-first
    (`ambient_footprint`'s own contract), so `actual_largest` is simply `files[0]`.
    """
    superpowers = next((f for f in files if f.path == SUPERPOWERS_SKILL_PATH), None)
    largest = files[0] if files else None
    holds = superpowers is not None and largest is not None and superpowers.path == largest.path
    return holds, superpowers, largest


# --- .mcp.json: what a snapshot can and cannot say ------------------------------------------


@dataclass(slots=True)
class McpDeclaration:
    servers: list[str]
    declaration_bytes: int


def mcp_declaration(project_dir: Path) -> McpDeclaration | None:
    """The declared server list and the byte size of the config that names them.

    Never the tool schemas those servers would advertise at connect time — see
    `LIMIT_UNMEASURABLE_MCP`.
    """
    path = project_dir / ".mcp.json"
    if not path.is_file():
        return None
    raw = path.read_bytes()
    data = json.loads(raw.decode("utf-8"))
    servers = sorted(data.get("mcpServers", {}).keys())
    return McpDeclaration(servers=servers, declaration_bytes=len(raw))


# --- SessionStart / UserPromptSubmit traffic: measured, not estimated ----------------------


@dataclass(slots=True)
class InjectionSizeStats:
    hook_event: str
    n: int
    median_bytes: float
    max_bytes: int
    sessions: int = 0
    max_records_in_one_session: int = 0


def _content_bytes(event: Event) -> int:
    return len(event.text.encode("utf-8"))


def session_start_injection_stats(
    paths: list[Path], *, since: str | None = None
) -> dict[str, InjectionSizeStats]:
    """Median and max byte size of real `hook_inject` records, per hook event.

    Grouped by `event.name` (the hook event: `SessionStart`, `UserPromptSubmit`, ...). A
    `SessionStart` moment can carry several hooks' output batched into one record — see
    `replay.transcript._injected_text` — so this also reports, per event kind, how many records
    landed in a single session at most, which is the reason a per-record max understates the
    true cold-start cost when several `SessionStart` hooks fire back to back in one file.
    """
    sizes: dict[str, list[int]] = {}
    per_session_counts: dict[str, dict[str, int]] = {}
    for path in paths:
        session_id = str(path)
        for event in iter_events(path):
            if event.kind != "hook_inject" or not event.name:
                continue
            day = event.timestamp[:10]
            if since and day and day < since:
                continue
            key = event.name
            sizes.setdefault(key, []).append(_content_bytes(event))
            counts = per_session_counts.setdefault(key, {})
            counts[session_id] = counts.get(session_id, 0) + 1

    stats: dict[str, InjectionSizeStats] = {}
    for key, values in sizes.items():
        counts = per_session_counts.get(key, {})
        stats[key] = InjectionSizeStats(
            hook_event=key,
            n=len(values),
            median_bytes=statistics.median(values),
            max_bytes=max(values),
            sessions=len(counts),
            max_records_in_one_session=max(counts.values()) if counts else 0,
        )
    return stats


# --- findings --------------------------------------------------------------------------------


def _table_lines(rows: list[SectionBudget], *, top: int | None = None) -> str:
    shown = rows[:top] if top else rows
    lines = [f"{'section':<8s}{'bytes':>8s}{'est.tokens':>12s}{'% of file':>10s}  title"]
    for r in shown:
        lines.append(
            f"§{r.id:<7s}{r.num_bytes:>8d}{r.est_tokens:>12.0f}{r.fraction * 100:>9.1f}%  "
            f"{r.title[:70]}"
        )
    return "\n".join(lines)


def build_findings(
    snapshot_dir: Path,
    *,
    snapshot_id: str,
    transcript_paths: list[Path] | None = None,
    since: str | None = None,
) -> list[Finding]:
    """The BUDGET check's findings: one COSTLY total, the rest INFO — this check ranks a cost,
    not a broken mechanism (docs/METHOD.md's severity ordering)."""
    project = snapshot_dir / "project"
    claude_md = (project / "CLAUDE.md").read_text(encoding="utf-8")
    manifest = json.loads((snapshot_dir / "manifest.json").read_text(encoding="utf-8"))

    findings: list[Finding] = []

    # --- 1. the headline number: CLAUDE.md alone, as a fraction of an assumed window --------
    claude_md_bytes = len(claude_md.encode("utf-8"))
    claude_md_tokens = estimate_tokens(claude_md_bytes)
    fraction_of_window = claude_md_tokens / ASSUMED_CONTEXT_WINDOW_TOKENS
    findings.append(
        Finding(
            id="budget-claude-md-total",
            check="BUDGET",
            severity=Severity.COSTLY,
            summary=(
                f"CLAUDE.md is {claude_md_bytes:,} bytes ≈ {claude_md_tokens:,.0f} estimated "
                f"tokens ({fraction_of_window * 100:.1f}% of an assumed "
                f"{ASSUMED_CONTEXT_WINDOW_TOKENS:,}-token window) spent before the first user "
                "word, every session."
            ),
            snapshot=snapshot_id,
            evidence=(Evidence(file="CLAUDE.md"),),
            detail=(
                f"estimator: {ESTIMATOR}. assumed context window: "
                f"{ASSUMED_CONTEXT_WINDOW_TOKENS:,} tokens (not read from any config — a named "
                "assumption, since window size varies by model and beta flag)."
            ),
            limit=LIMIT_ESTIMATE,
        )
    )

    # --- 2. the reliable part: the per-section ratio table ---------------------------------
    sections = claude_md_section_table(claude_md)
    accounted = sum(r.num_bytes for r in sections)
    residual = claude_md_bytes - accounted
    table = _table_lines(sections)
    findings.append(
        Finding(
            id="budget-claude-md-sections",
            check="BUDGET",
            severity=Severity.INFO,
            summary=(
                f"CLAUDE.md's {len(sections)} sections, ranked by byte share — the reliable "
                "part of this check (the ratio survives estimator error even though the "
                "absolute totals do not)."
            ),
            snapshot=snapshot_id,
            evidence=(Evidence(file="CLAUDE.md"),),
            detail=(
                f"{table}\n\npreamble + tiling residual (text before the first heading, and "
                f"any line-join rounding): {residual} bytes "
                f"({residual / claude_md_bytes * 100:.1f}% of the file)."
            ),
            limit=LIMIT_ESTIMATE,
        )
    )

    # --- 3. the ambient layer: a ceiling, and the superpowers claim checked against it ------
    ambient_files = ambient_footprint(manifest)
    ambient_total = sum(f.num_bytes for f in ambient_files)
    holds, superpowers, largest = check_superpowers_largest_claim(ambient_files)
    if superpowers is None:
        claim_text = (
            "the plan's claimed file is not present in this snapshot's ambient census at all."
        )
    elif holds:
        claim_text = (
            f"VERIFIED: using-superpowers/SKILL.md ({superpowers.num_bytes:,} bytes) is the "
            "largest file in the ambient layer."
        )
    else:
        assert largest is not None
        claim_text = (
            f"REFUTED by file size: using-superpowers/SKILL.md is {superpowers.num_bytes:,} "
            f"bytes, {sum(1 for f in ambient_files if f.num_bytes > superpowers.num_bytes)} "
            f"other ambient files are larger, and the largest on disk is `{largest.path}` at "
            f"{largest.num_bytes:,} bytes. Real SessionStart traffic (see "
            "budget-sessionstart-traffic) separately confirms using-superpowers' body IS "
            "injected whole every time it fires (measured 5,648 bytes in the live corpus, "
            "2026-08-29) — the plan's claim about what gets INJECTED may still be right even "
            "though the file-size ranking that would evidence it is not, because most larger "
            "ambient skill files are never injected in full at all (see LIMIT_AMBIENT_CEILING)."
        )
    findings.append(
        Finding(
            id="budget-ambient",
            check="BUDGET",
            severity=Severity.INFO,
            summary=(
                f"ambient layer (~/.claude): {len(ambient_files)} files, {ambient_total:,} "
                f"bytes on disk (≈{estimate_tokens(ambient_total):,.0f} estimated tokens as a "
                "ceiling, not a measured injection). "
                f"{claim_text}"
            ),
            snapshot=snapshot_id,
            evidence=(Evidence(file="ambient/", run_id=snapshot_id),),
            detail=_table_lines(
                [SectionBudget(f.path, "", f.num_bytes, estimate_tokens(f.num_bytes),
                                f.num_bytes / (ambient_total or 1)) for f in ambient_files],
                top=10,
            ),
            limit=LIMIT_AMBIENT_CEILING,
        )
    )

    # --- 4. MCP: what .mcp.json says, and the plan's stated omission confirmed -------------
    mcp = mcp_declaration(project)
    if mcp is None:
        summary = "no .mcp.json in this snapshot — no MCP servers declared."
        detail = None
    else:
        summary = (
            f".mcp.json declares {len(mcp.servers)} MCP server(s) "
            f"({', '.join(mcp.servers) or 'none'}) in {mcp.declaration_bytes} bytes of config. "
            "Tool schemas advertised by those servers at connect time are NOT measured — see "
            "limit."
        )
        detail = (
            f"declared servers: {mcp.servers}. Each server, once connected, advertises its own "
            "tools with a name, description, and JSON Schema per tool — real prompt content "
            "this check cannot see from a filesystem snapshot."
        )
    findings.append(
        Finding(
            id="budget-mcp-unmeasured",
            check="BUDGET",
            severity=Severity.INFO,
            summary=summary,
            snapshot=snapshot_id,
            evidence=(Evidence(file=".mcp.json"),),
            detail=detail,
            limit=LIMIT_UNMEASURABLE_MCP,
        )
    )

    # --- 5. real SessionStart / UserPromptSubmit traffic ------------------------------------
    if transcript_paths:
        stats = session_start_injection_stats(transcript_paths, since=since)
        rows = []
        for key in ("SessionStart", "UserPromptSubmit"):
            s = stats.get(key)
            if s is None:
                rows.append(f"{key}: no hook_inject events found")
                continue
            rows.append(
                f"{key}: n={s.n} records across {s.sessions} sessions, "
                f"median={s.median_bytes:,.0f}B (~{estimate_tokens(s.median_bytes):,.0f} tok), "
                f"max={s.max_bytes:,}B (~{estimate_tokens(s.max_bytes):,.0f} tok), "
                f"up to {s.max_records_in_one_session} records batched into a single session's "
                f"{key}"
            )
        findings.append(
            Finding(
                id="budget-sessionstart-traffic",
                check="BUDGET",
                severity=Severity.INFO,
                summary=(
                    "real hook_inject traffic, measured (not estimated) from "
                    f"{len(transcript_paths)} transcripts: "
                    + "; ".join(rows)
                ),
                snapshot=snapshot_id,
                evidence=(Evidence(run_id=f"transcripts ({len(transcript_paths)} files)"),),
                detail="\n".join(rows),
                limit=LIMIT_REAL_TRAFFIC,
            )
        )
    else:
        findings.append(
            Finding(
                id="budget-sessionstart-traffic-unmeasured",
                check="BUDGET",
                severity=Severity.INFO,
                summary=(
                    "no transcripts supplied — SessionStart/UserPromptSubmit traffic not "
                    "measured."
                ),
                snapshot=snapshot_id,
                evidence=(Evidence(run_id="none"),),
                limit=(
                    "This run was given no transcript paths. The number this row would carry "
                    "is real, measured traffic, not something this check can substitute an "
                    "estimate for — see docs/METHOD.md's silence-is-not-absence rule."
                ),
            )
        )

    return findings


__all__ = [
    "AmbientFile",
    "ASSUMED_CONTEXT_WINDOW_TOKENS",
    "BYTES_PER_TOKEN",
    "ESTIMATOR",
    "InjectionSizeStats",
    "McpDeclaration",
    "SUPERPOWERS_SKILL_PATH",
    "SectionBudget",
    "ambient_footprint",
    "build_findings",
    "check_superpowers_largest_claim",
    "claude_md_section_table",
    "estimate_tokens",
    "mcp_declaration",
    "session_start_injection_stats",
]
