"""A04 — render `ARCHITECTURE.generated.md` from an architecture index.

A **projection**, and nothing else. It adds no fact the artifact does not contain, no severity, no
ranking and no recommendation; it reorganises records into tables a person can read. Its name and
its header both say it is generated, because the repo already carries the cost of a hand-drifted
copy of a generated document (`DOCS-FOR-NOTEBOOKLLM/CLAUDE.md`, four decisions stale per
`docs/ROADMAP.md`).

The header carries the same provenance the artifact does — commit, dirty disclosure, extractor
version and hash, aggregate identity — so a reader who sees only the markdown can still tell what
it is valid for. Gaps are rendered, never omitted: a projection that hides the unknowns is more
dangerous than no projection, because it reads as complete.
"""

from __future__ import annotations

from typing import Any

MAX_LISTED_DIRTY_PATHS = 50


def _of_kind(artifact: dict[str, Any], kind: str) -> list[dict[str, Any]]:
    return sorted(
        (record for record in artifact.get("records", []) if record.get("kind") == kind),
        key=lambda record: record.get("id", ""),
    )


def _cite(record: dict[str, Any]) -> str:
    provenance = record.get("provenance") or {}
    path = provenance.get("path", "?")
    line = provenance.get("line")
    return f"`{path}:{line}`" if line else f"`{path}`"


def _header(artifact: dict[str, Any]) -> list[str]:
    repository = artifact["repository"]
    scope = repository["source_scope"]
    extractor = artifact["extractor"]
    head = repository["head"] or "unknown"
    lines = [
        "<!-- Code generated by bearhug arch render. DO NOT EDIT. -->",
        "<!-- Regenerate: bearhug arch render docs/architecture/index.json"
        " --out docs/architecture/ARCHITECTURE.generated.md -->",
        "",
        "# Architecture index",
        "",
        "A projection of `docs/architecture/index.json`. Every fact below is extracted from source",
        "at one commit; nothing here is inferred, ranked, or judged. This document is **valid only",
        "for the commit recorded below** — against any other head it is stale.",
        "",
        "## Provenance",
        "",
        "| | |",
        "|---|---|",
        f"| Commit | `{head}` |",
        f"| Working tree | {'DIRTY' if repository['dirty'] else 'clean'} "
        f"({len(repository['dirty_paths'])} path(s)) |",
        f"| Generated at | {artifact['generated_at']} |",
        f"| Extractor | `{extractor['name']}` {extractor['version']}"
        f" (`{extractor['sha256'][:12]}`) |",
        f"| Records identity | `{artifact['identity']['records_sha256'][:12]}` |",
        f"| Schema version | {artifact['schema_version']} |",
        "",
    ]
    if repository["dirty"]:
        lines += [
            "> **The tree was dirty when this was extracted.** It therefore describes neither the",
            "> commit above nor any commit. The modified paths were:",
            ">",
        ]
        for path in repository["dirty_paths"][:MAX_LISTED_DIRTY_PATHS]:
            lines.append(f"> - `{path}`")
        remaining = len(repository["dirty_paths"]) - MAX_LISTED_DIRTY_PATHS
        if remaining > 0:
            lines.append(f"> - …and {remaining} more")
        lines.append("")

    lines += [
        "## Scope of the scan",
        "",
        "A package absent from this document may be a package outside the scan, not a package that",
        "does not exist. The scan entered:",
        "",
        "| module | directory |",
        "|---|---|",
    ]
    for module in scope["modules"]:
        lines.append(f"| `{module['path']}` | `{module['dir']}` |")
    if not scope["modules"]:
        lines.append("| _none_ | _no Go module was found in scope_ |")
    lines += [
        "",
        f"Excluded directory names: {', '.join(f'`{name}`' for name in scope['excluded'])}.",
        f"Files above {scope['max_file_bytes']} bytes are reported as parse failures.",
        "",
    ]
    return lines


def _packages(artifact: dict[str, Any]) -> list[str]:
    packages = _of_kind(artifact, "package")
    tests = {record["package"]: record for record in _of_kind(artifact, "test_mapping")}
    entries = {record["package"]: record for record in _of_kind(artifact, "entry_point")}
    lines = [
        "## Packages",
        "",
        f"{len(packages)} package(s), each with the directory that owns it.",
        "",
        "| package | name | directory | module | tests | entry point | cited |",
        "|---|---|---|---|---|---|---|",
    ]
    for record in packages:
        import_path = record["import_path"]
        mapping = tests.get(import_path)
        test_cell = (
            f"{mapping['test_function_count']} in {len(mapping['test_files'])} file(s)"
            if mapping
            else "—"
        )
        entry = entries.get(import_path)
        lines.append(
            f"| `{import_path}` | `{record['name']}` | `{record['dir']}` | "
            f"`{record['module']}` | {test_cell} | "
            f"{entry['convention'] if entry else '—'} | {_cite(record)} |"
        )
    if not packages:
        lines.append("| _none_ | | | | | | |")
    lines.append("")
    return lines


def _edges(artifact: dict[str, Any]) -> list[str]:
    edges = _of_kind(artifact, "edge")
    crossing = [edge for edge in edges if edge["from_module"] != edge["to_module"]]
    lines = [
        "## Internal import edges",
        "",
        f"{len(edges)} package-level edge(s), of which {len(crossing)} cross a module boundary.",
        "Both endpoints of every edge resolve to a module in scope; an import that does not is a",
        "dependency, and an import that resolves to nothing is an `unknown` below.",
        "",
        "| from | to | crosses modules | cited |",
        "|---|---|---|---|",
    ]
    for edge in edges:
        crosses = "yes" if edge["from_module"] != edge["to_module"] else ""
        lines.append(f"| `{edge['from']}` | `{edge['to']}` | {crosses} | {_cite(edge)} |")
    if not edges:
        lines.append("| _none_ | | | |")
    lines.append("")
    return lines


def _dependencies(artifact: dict[str, Any]) -> list[str]:
    dependencies = _of_kind(artifact, "dependency")
    by_module: dict[str, set[str]] = {}
    for record in dependencies:
        by_module.setdefault(record["module_path"], set()).add(record["package"])
    lines = [
        "## Dependencies",
        "",
        f"{len(dependencies)} dependency record(s) over {len(by_module)} distinct import root(s).",
        "These are imports that resolve to no module in scope. They are **not** graph edges.",
        "",
        "| import root | importing packages |",
        "|---|---|",
    ]
    for module_path in sorted(by_module):
        lines.append(f"| `{module_path}` | {len(by_module[module_path])} |")
    if not dependencies:
        lines.append("| _none_ | |")
    lines.append("")
    return lines


def _entry_points(artifact: dict[str, Any]) -> list[str]:
    entries = _of_kind(artifact, "entry_point")
    under_cmd = [entry for entry in entries if entry["convention"] == "cmd"]
    other = [entry for entry in entries if entry["convention"] != "cmd"]
    lines = [
        "## Entry points",
        "",
        f"{len(entries)} package(s) declaring `package main`: {len(under_cmd)} under a `cmd/` "
        f"path, {len(other)} elsewhere.",
        "",
        "| package | directory | convention | cited |",
        "|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            f"| `{entry['package']}` | `{entry['dir']}` | {entry['convention']} | {_cite(entry)} |"
        )
    if not entries:
        lines.append("| _none_ | | | |")
    lines.append("")
    return lines


def _generated(artifact: dict[str, Any]) -> list[str]:
    generated = _of_kind(artifact, "generated_file")
    lines = [
        "## Generated files",
        "",
        f"{len(generated)} file(s) carrying Go's canonical generated marker before the package",
        "clause. Detection is by marker only — a filename is not evidence.",
        "",
        "| file | marker line |",
        "|---|---|",
    ]
    for record in generated:
        lines.append(f"| `{record['path']}` | {record['marker_line']} |")
    if not generated:
        lines.append("| _none_ | |")
    lines.append("")
    return lines


def _decisions(artifact: dict[str, Any]) -> list[str]:
    links = _of_kind(artifact, "decision_link")
    by_path: dict[str, set[str]] = {}
    for link in links:
        by_path.setdefault(link["cites_path"], set()).add(link["decision_id"])
    lines = [
        "## Decision links",
        "",
        f"{len(links)} link(s) from a `docs/memex` record's `evidence:` to a path, over",
        f"{len(by_path)} distinct path(s). A `#fragment` is retained verbatim and never resolved",
        "to a declaration. These records are measured by the lab, not extracted from product",
        "source: they are true of the snapshot they were read from.",
        "",
        "| cited path | decisions |",
        "|---|---|",
    ]
    for path in sorted(by_path):
        ids = ", ".join(sorted(by_path[path], key=lambda value: int(value)))
        lines.append(f"| `{path}` | {ids} |")
    if not links:
        lines.append("| _none_ | |")
    lines.append("")
    return lines


def _components(artifact: dict[str, Any]) -> list[str]:
    components = _of_kind(artifact, "harness_component")
    unregistered = [record for record in components if not record["registrations"]]
    lines = [
        "## Harness components",
        "",
        f"{len(components)} script(s) under `scripts/hooks/`, of which {len(unregistered)} carry",
        "no registration in `.claude/settings.json`.",
        "",
        "An empty registration list means exactly that: nothing in `settings.json` names this",
        "file. It does **not** mean the script never runs — a test file, an imported library",
        "module, and a script another hook invokes all appear here with an empty list.",
        "",
        "| script | registrations |",
        "|---|---|",
    ]
    for record in components:
        if record["registrations"]:
            shown = ", ".join(
                f"{item['event']}" + (f"/{item['matcher']}" if item["matcher"] else "")
                for item in record["registrations"]
            )
        else:
            shown = "_none_"
        lines.append(f"| `{record['script']}` | {shown} |")
    if not components:
        lines.append("| _none_ | |")
    lines.append("")
    return lines


def _gaps(artifact: dict[str, Any]) -> list[str]:
    unknowns = _of_kind(artifact, "unknown")
    failures = sorted(
        artifact.get("parse_failures", []), key=lambda failure: failure.get("path", "")
    )
    lines = [
        "## Gaps",
        "",
        "What the extractor could not resolve. These are recorded rather than guessed: an edge",
        "that is merely probable is not in this index at any confidence.",
        "",
        f"### Unresolved facts ({len(unknowns)})",
        "",
        "| subject | reason | cited |",
        "|---|---|---|",
    ]
    for record in unknowns:
        lines.append(
            f"| `{record['subject']}` | `{record['reason']}` | {_cite(record)} |"
        )
    if not unknowns:
        lines.append("| _none_ | | |")
    lines += [
        "",
        f"### Parse failures ({len(failures)})",
        "",
        "| file | reason |",
        "|---|---|",
    ]
    for failure in failures:
        lines.append(f"| `{failure['path']}` | `{failure['reason']}` |")
    if not failures:
        lines.append("| _none_ | |")
    lines.append("")
    return lines


def render_markdown(artifact: dict[str, Any]) -> str:
    """Render one artifact as `ARCHITECTURE.generated.md`. Deterministic for a given artifact."""
    lines: list[str] = []
    lines += _header(artifact)
    lines += _packages(artifact)
    lines += _entry_points(artifact)
    lines += _edges(artifact)
    lines += _dependencies(artifact)
    lines += _generated(artifact)
    lines += _decisions(artifact)
    lines += _components(artifact)
    lines += _gaps(artifact)
    return "\n".join(lines).rstrip() + "\n"


__all__ = ["render_markdown"]
