"""Check installed runtime dependencies without running hooks or creating evidence."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# Isolation and -B keep ambient modules and generated bytecode out of this installation check.
# Importing the exact host parser reproduces the dependency failure a runtime-only copy hides.
_PROBE = """
import json, sys
from pathlib import Path
hooks = Path(sys.argv[1])
sys.path.insert(0, str(hooks))
try:
    import _bearhug
    from _bearhug.readers import _boardrows
    parser = _boardrows()
    assert Path(_bearhug.__file__).resolve().parent == hooks / '_bearhug'
    assert Path(parser.__file__).resolve() == hooks / 'boardrows.py'
    assert callable(parser._split_cells) and hasattr(parser._ROW, 'match')
    print(json.dumps({
        'status': 'ready',
        'reason': 'installed runtime and shared BOARD parser import successfully',
        'runtime_version': _bearhug.runtime_version(),
        'runtime_sha256': _bearhug.runtime_sha256(),
    }))
except Exception as exc:
    print(json.dumps({'status': 'error', 'reason': type(exc).__name__}))
    sys.exit(1)
"""


def verify_runtime(subject: Path) -> dict:
    """Verify the installed import boundary, not provider loading or live hook behavior."""
    hooks = subject.resolve() / "scripts" / "hooks"
    try:
        completed = subprocess.run(
            [sys.executable, "-I", "-B", "-c", _PROBE, str(hooks)],
            stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=15,
        )
        result = json.loads(completed.stdout)
        if not isinstance(result, dict) or result.get("status") not in {"ready", "error"}:
            raise ValueError("invalid runtime probe response")
        if completed.returncode != 0 and result["status"] == "ready":
            raise ValueError("runtime probe failed")
    except (OSError, subprocess.SubprocessError, ValueError) as exc:
        result = {"status": "error", "reason": f"runtime probe failed: {type(exc).__name__}"}
    result["live_hook_execution_verified"] = False
    return result
