"""Provider-neutral session evidence adapters.

The adapters normalize a provider's raw event stream.  They do not decide whether a
session is acceptable for a campaign; policy consumes the explicit observations and
limitations in the normalized result.
"""

from bearhug.providers.app_server_client import (
    AppServerClientError,
    AppServerExchange,
    AppServerRun,
    run_codex_app_server,
)
from bearhug.providers.claude import (
    ClaudeEventError,
    ClaudeLaunchContract,
    ClaudeNormalization,
    NormalizedClaudeEvent,
    build_claude_command,
    normalize_claude_jsonl,
)
from bearhug.providers.claude_client import ClaudeClientError, ClaudeRun, run_claude
from bearhug.providers.codex import (
    CodexEventError,
    CodexLaunchContract,
    CodexNormalization,
    build_codex_command,
    normalize_codex_jsonl,
)
from bearhug.providers.codex_app_server import (
    AppServerEventError,
    CodexAppServerContract,
    CodexAppServerNormalization,
    build_app_server_command,
    build_initialize_messages,
    build_turn_start_message,
    normalize_app_server_jsonl,
)
from bearhug.providers.custody import ProviderCustodyError, ProviderCustodyStore
from bearhug.providers.event_journal import (
    ProviderEventAdapterGap,
    ProviderEventJournalError,
    append_provider_event,
    build_provider_event,
    event_sha256,
    events_from_app_server_normalization,
    events_from_claude_normalization,
    read_event_journal,
    validate_event_journal,
    validate_provider_event,
)
from bearhug.providers.failure_receipt import (
    ProviderFailureReceiptError,
    build_provider_failure_receipt,
    observed_app_server_identity,
    observed_claude_identity,
    validate_provider_failure_receipt,
    write_provider_failure_receipt,
)
from bearhug.providers.final_output import ProviderFinalOutputError, strict_final_json
from bearhug.providers.observation import (
    ProviderObservationError,
    observation_from_receipt,
    provider_observations,
    validate_provider_observation,
)
from bearhug.providers.policy import (
    ALL_CAPABILITIES,
    CAPABILITIES_BY_PROVIDER,
    ProviderPolicy,
    ProviderPolicyError,
    ProviderRole,
    load_provider_policy,
    provider_role,
    validate_provider_policy,
)
from bearhug.providers.qualification_index import (
    ProviderQualificationIndex,
    ProviderQualificationIndexError,
    QualifiedProvider,
    load_provider_qualification_index,
)
from bearhug.providers.receipt import (
    CandidateResult,
    CloseRepository,
    LaunchRepository,
    ProviderReceiptError,
    argv_sha256,
    capture_close_repository,
    capture_launch_repository,
    receipt_from_app_server,
    receipt_from_claude,
    validate_provider_receipt,
    write_provider_receipt,
)
from bearhug.providers.runtime_attestation import (
    RuntimeAttestationError,
    build_claude_runtime_attestation,
    build_codex_runtime_attestation,
    build_runtime_attestation,
    claude_runtime_event_observations,
    codex_runtime_event_observations,
    validate_runtime_attestation,
    write_runtime_attestation,
)

__all__ = [
    "AppServerClientError",
    "AppServerExchange",
    "AppServerRun",
    "run_codex_app_server",
    "ClaudeClientError",
    "ClaudeEventError",
    "ClaudeLaunchContract",
    "ClaudeNormalization",
    "ClaudeRun",
    "NormalizedClaudeEvent",
    "build_claude_command",
    "normalize_claude_jsonl",
    "run_claude",
    "CodexEventError",
    "CodexLaunchContract",
    "CodexNormalization",
    "build_codex_command",
    "normalize_codex_jsonl",
    "AppServerEventError",
    "CodexAppServerContract",
    "CodexAppServerNormalization",
    "build_app_server_command",
    "build_initialize_messages",
    "build_turn_start_message",
    "normalize_app_server_jsonl",
    "ProviderFailureReceiptError",
    "ProviderCustodyError",
    "ProviderCustodyStore",
    "ProviderFinalOutputError",
    "build_provider_failure_receipt",
    "observed_app_server_identity",
    "observed_claude_identity",
    "validate_provider_failure_receipt",
    "write_provider_failure_receipt",
    "ProviderEventAdapterGap",
    "ProviderEventJournalError",
    "append_provider_event",
    "build_provider_event",
    "event_sha256",
    "events_from_app_server_normalization",
    "events_from_claude_normalization",
    "read_event_journal",
    "validate_event_journal",
    "validate_provider_event",
    "ProviderObservationError",
    "ProviderQualificationIndex",
    "ProviderQualificationIndexError",
    "QualifiedProvider",
    "observation_from_receipt",
    "provider_observations",
    "load_provider_qualification_index",
    "validate_provider_observation",
    "CandidateResult",
    "CloseRepository",
    "LaunchRepository",
    "ProviderReceiptError",
    "argv_sha256",
    "capture_close_repository",
    "capture_launch_repository",
    "receipt_from_app_server",
    "receipt_from_claude",
    "validate_provider_receipt",
    "write_provider_receipt",
    "RuntimeAttestationError",
    "build_claude_runtime_attestation",
    "build_codex_runtime_attestation",
    "build_runtime_attestation",
    "claude_runtime_event_observations",
    "codex_runtime_event_observations",
    "validate_runtime_attestation",
    "write_runtime_attestation",
    "strict_final_json",
    "ALL_CAPABILITIES",
    "CAPABILITIES_BY_PROVIDER",
    "ProviderPolicy",
    "ProviderPolicyError",
    "ProviderRole",
    "load_provider_policy",
    "provider_role",
    "validate_provider_policy",
]
