"""Exact, privacy-bounded contract for Codex App Server ``request_user_input``.

This module describes only the wire shape generated by ``codex-cli 0.153.0-alpha.5``.  It does
not install a hook, decide whether a question should be asked, or answer one automatically.
Question and answer prose exists only in raw custody supplied to or returned by the explicitly
named raw functions.  The validated records retain correlation metadata, counts and digests.
The generated schemas leave text and several arrays unbounded; Bear Hug's custody contract adds
finite limits without representing those limits as native Codex policy.

``item/tool/requestUserInput`` is an interactive tool request.  It is deliberately not treated as
a Codex ``PermissionRequest`` or an App Server ``*/requestApproval`` request.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any


class CodexUserInputContractError(ValueError):
    """Raw custody or protocol identity does not satisfy the sealed contract."""


PROVIDER = "openai-codex"
PROVIDER_VERSION = "codex-cli 0.153.0-alpha.5"
ADAPTER = "codex-app-server-stdio"
REQUEST_METHOD = "item/tool/requestUserInput"
PARAMS_SCHEMA_TITLE = "ToolRequestUserInputParams"
PARAMS_SCHEMA_SHA256 = "fda15b62e7446105b59c8ed85c908abed2a47db70653e57c92c47a2f204fa77a"
RESPONSE_SCHEMA_TITLE = "ToolRequestUserInputResponse"
RESPONSE_SCHEMA_SHA256 = "5073b245f741fa8ce62ec52e4dd1809b7831f9c4284c279a78abc9b171f8e3f2"

_REQUEST_FIELDS = frozenset({"id", "method", "params"})
_PARAM_REQUIRED_FIELDS = frozenset({"isBlocking", "itemId", "questions", "threadId", "turnId"})
_PARAM_OPTIONAL_FIELDS = frozenset({"autoResolutionMs"})
_QUESTION_REQUIRED_FIELDS = frozenset({"header", "id", "question"})
_QUESTION_OPTIONAL_FIELDS = frozenset({"isOther", "isSecret", "options"})
_OPTION_FIELDS = frozenset({"description", "label"})
_RESPONSE_FIELDS = frozenset({"id", "result"})
_RESULT_FIELDS = frozenset({"answers"})
_ANSWER_FIELDS = frozenset({"answers"})

_MAX_RAW_BYTES = 64 * 1024
_MAX_IDENTIFIER_BYTES = 256
_MAX_HEADER_CHARACTERS = 12
_MAX_QUESTION_BYTES = 4096
_MAX_OPTION_LABEL_BYTES = 256
_MAX_OPTION_DESCRIPTION_BYTES = 2048
_MAX_ANSWER_BYTES = 4096
_MAX_ANSWERS_PER_QUESTION = 3
_UINT64_MAX = 2**64 - 1
_INT64_MIN = -(2**63)
_INT64_MAX = 2**63 - 1


@dataclass(frozen=True, slots=True)
class CodexUserInputProtocolIdentity:
    """The exact provider and generated-schema evidence this contract was reviewed against."""

    provider: str = PROVIDER
    provider_version: str = PROVIDER_VERSION
    adapter: str = ADAPTER
    request_method: str = REQUEST_METHOD
    params_schema_title: str = PARAMS_SCHEMA_TITLE
    params_schema_sha256: str = PARAMS_SCHEMA_SHA256
    response_schema_title: str = RESPONSE_SCHEMA_TITLE
    response_schema_sha256: str = RESPONSE_SCHEMA_SHA256


EXACT_PROTOCOL_IDENTITY = CodexUserInputProtocolIdentity()


@dataclass(frozen=True, slots=True)
class CodexUserInputQuestionEvidence:
    """Non-prose facts retained for one validated question.

    ``question_id`` is retained because the response map uses it as its operational correlation
    key.  The header, question, option labels and option descriptions remain digest-only.
    """

    question_id: str
    content_sha256: str
    content_byte_count: int
    option_count: int | None
    is_other: bool
    is_secret: bool


@dataclass(frozen=True, slots=True)
class CodexUserInputRequestEvidence:
    """Digest-only evidence for one request whose raw bytes remain in separate custody."""

    protocol: CodexUserInputProtocolIdentity
    request_id: str | int
    thread_id: str
    turn_id: str
    item_id: str
    is_blocking: bool
    auto_resolution_ms: int | None
    questions: tuple[CodexUserInputQuestionEvidence, ...]
    raw_sha256: str
    raw_byte_count: int


@dataclass(frozen=True, slots=True)
class CodexUserInputAnswerEvidence:
    """Digest-only evidence for the complete answer list to one question."""

    question_id: str
    content_sha256: str
    content_byte_count: int
    answer_count: int


@dataclass(frozen=True, slots=True)
class CodexUserInputResponseEvidence:
    """Digest-only evidence for a response correlated to one validated request."""

    protocol: CodexUserInputProtocolIdentity
    request_id: str | int
    thread_id: str
    turn_id: str
    item_id: str
    answers: tuple[CodexUserInputAnswerEvidence, ...]
    raw_sha256: str
    raw_byte_count: int


def _require_exact_protocol(identity: CodexUserInputProtocolIdentity) -> None:
    if not isinstance(identity, CodexUserInputProtocolIdentity):
        raise CodexUserInputContractError("protocol identity has the wrong type")
    if identity != EXACT_PROTOCOL_IDENTITY:
        raise CodexUserInputContractError(
            "request_user_input requires the exact reviewed provider and schema identity"
        )


def _reject_constant(value: str) -> None:
    raise CodexUserInputContractError(f"non-finite JSON number is forbidden: {value}")


def _closed_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise CodexUserInputContractError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _parse_raw(raw: bytes, *, where: str) -> dict[str, Any]:
    if not isinstance(raw, bytes):
        raise CodexUserInputContractError(f"{where} raw custody must be exact bytes")
    if not raw or len(raw) > _MAX_RAW_BYTES:
        raise CodexUserInputContractError(
            f"{where} raw custody must contain 1..{_MAX_RAW_BYTES} bytes"
        )
    try:
        value = json.loads(
            raw,
            object_pairs_hook=_closed_object,
            parse_constant=_reject_constant,
        )
    except UnicodeDecodeError as exc:
        raise CodexUserInputContractError(f"{where} raw custody is not UTF-8") from exc
    except json.JSONDecodeError as exc:
        raise CodexUserInputContractError(f"{where} raw custody is not one JSON value") from exc
    if not isinstance(value, dict):
        raise CodexUserInputContractError(f"{where} must be an object")
    return value


def _exact(value: Any, fields: frozenset[str], where: str) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != fields:
        raise CodexUserInputContractError(f"{where} has missing or unknown fields")
    return value


def _required_optional(
    value: Any, required: frozenset[str], optional: frozenset[str], where: str
) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise CodexUserInputContractError(f"{where} must be an object")
    fields = set(value)
    if not required <= fields or not fields <= required | optional:
        raise CodexUserInputContractError(f"{where} has missing or unknown fields")
    return value


def _text(value: Any, *, where: str, max_bytes: int, allow_empty: bool = False) -> str:
    if not isinstance(value, str):
        raise CodexUserInputContractError(f"{where} must be a string")
    try:
        encoded = value.encode("utf-8")
    except UnicodeEncodeError as exc:
        raise CodexUserInputContractError(f"{where} is not valid UTF-8 text") from exc
    if (not allow_empty and not value) or len(encoded) > max_bytes:
        minimum = 0 if allow_empty else 1
        raise CodexUserInputContractError(
            f"{where} must contain {minimum}..{max_bytes} UTF-8 bytes"
        )
    if any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise CodexUserInputContractError(f"{where} contains control characters")
    return value


def _identifier(value: Any, where: str) -> str:
    result = _text(value, where=where, max_bytes=_MAX_IDENTIFIER_BYTES)
    if result != result.strip():
        raise CodexUserInputContractError(f"{where} must not have surrounding whitespace")
    return result


def _request_id(value: Any, where: str) -> str | int:
    if isinstance(value, str):
        return _identifier(value, where)
    if type(value) is int and _INT64_MIN <= value <= _INT64_MAX:
        return value
    raise CodexUserInputContractError(f"{where} must be a bounded string or signed 64-bit integer")


def _canonical_json(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            allow_nan=False,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
    except (TypeError, ValueError, UnicodeEncodeError) as exc:
        raise CodexUserInputContractError(f"value is not canonical JSON: {exc}") from exc


def _content_evidence(value: Any) -> tuple[str, int]:
    raw = _canonical_json(value)
    return hashlib.sha256(raw).hexdigest(), len(raw)


def _same_request_id(actual: Any, expected: str | int, where: str) -> str | int:
    parsed = _request_id(actual, where)
    # JSON-RPC string "1" and integer 1 are distinct correlation identifiers.
    if type(parsed) is not type(expected) or parsed != expected:
        raise CodexUserInputContractError(f"{where} does not match request custody")
    return parsed


def validate_raw_user_input_request(
    raw: bytes,
    *,
    expected_request_id: str | int,
    expected_thread_id: str,
    expected_turn_id: str,
    expected_item_id: str,
    protocol: CodexUserInputProtocolIdentity,
) -> CodexUserInputRequestEvidence:
    """Validate raw server-request custody and return no question or option prose."""

    _require_exact_protocol(protocol)
    expected_request_id = _request_id(expected_request_id, "expected_request_id")
    expected_thread_id = _identifier(expected_thread_id, "expected_thread_id")
    expected_turn_id = _identifier(expected_turn_id, "expected_turn_id")
    expected_item_id = _identifier(expected_item_id, "expected_item_id")

    request = _exact(_parse_raw(raw, where="request"), _REQUEST_FIELDS, "request")
    request_id = _same_request_id(request["id"], expected_request_id, "request.id")
    if request["method"] != REQUEST_METHOD:
        raise CodexUserInputContractError(
            "request.method is not item/tool/requestUserInput; permission and approval requests "
            "are separate contracts"
        )
    params = _required_optional(
        request["params"], _PARAM_REQUIRED_FIELDS, _PARAM_OPTIONAL_FIELDS, "request.params"
    )
    thread_id = _identifier(params["threadId"], "request.params.threadId")
    turn_id = _identifier(params["turnId"], "request.params.turnId")
    item_id = _identifier(params["itemId"], "request.params.itemId")
    if thread_id != expected_thread_id:
        raise CodexUserInputContractError("request.params.threadId does not match request custody")
    if turn_id != expected_turn_id:
        raise CodexUserInputContractError("request.params.turnId does not match request custody")
    if item_id != expected_item_id:
        raise CodexUserInputContractError("request.params.itemId does not match request custody")
    is_blocking = params["isBlocking"]
    if type(is_blocking) is not bool:
        raise CodexUserInputContractError("request.params.isBlocking must be boolean")
    auto_resolution_ms = params.get("autoResolutionMs")
    if auto_resolution_ms is not None and (
        type(auto_resolution_ms) is not int or not 0 <= auto_resolution_ms <= _UINT64_MAX
    ):
        raise CodexUserInputContractError(
            "request.params.autoResolutionMs must be null or an unsigned 64-bit integer"
        )

    raw_questions = params["questions"]
    if not isinstance(raw_questions, list) or not 1 <= len(raw_questions) <= 3:
        raise CodexUserInputContractError("request.params.questions must contain 1..3 questions")
    questions: list[CodexUserInputQuestionEvidence] = []
    seen_ids: set[str] = set()
    for index, raw_question in enumerate(raw_questions):
        where = f"request.params.questions[{index}]"
        question = _required_optional(
            raw_question, _QUESTION_REQUIRED_FIELDS, _QUESTION_OPTIONAL_FIELDS, where
        )
        question_id = _identifier(question["id"], f"{where}.id")
        if question_id in seen_ids:
            raise CodexUserInputContractError(f"duplicate question id: {question_id}")
        seen_ids.add(question_id)
        header = _text(question["header"], where=f"{where}.header", max_bytes=_MAX_QUESTION_BYTES)
        if len(header) > _MAX_HEADER_CHARACTERS:
            raise CodexUserInputContractError(
                f"{where}.header must contain at most {_MAX_HEADER_CHARACTERS} characters"
            )
        _text(question["question"], where=f"{where}.question", max_bytes=_MAX_QUESTION_BYTES)
        is_other = question.get("isOther", False)
        is_secret = question.get("isSecret", False)
        if type(is_other) is not bool:
            raise CodexUserInputContractError(f"{where}.isOther must be boolean")
        if type(is_secret) is not bool:
            raise CodexUserInputContractError(f"{where}.isSecret must be boolean")

        raw_options = question.get("options")
        option_count: int | None
        if raw_options is None:
            option_count = None
        else:
            if not isinstance(raw_options, list) or not 2 <= len(raw_options) <= 3:
                raise CodexUserInputContractError(
                    f"{where}.options must be null or contain 2..3 options"
                )
            for option_index, raw_option in enumerate(raw_options):
                option_where = f"{where}.options[{option_index}]"
                option = _exact(raw_option, _OPTION_FIELDS, option_where)
                _text(
                    option["label"],
                    where=f"{option_where}.label",
                    max_bytes=_MAX_OPTION_LABEL_BYTES,
                )
                _text(
                    option["description"],
                    where=f"{option_where}.description",
                    max_bytes=_MAX_OPTION_DESCRIPTION_BYTES,
                )
            option_count = len(raw_options)
        content_sha256, content_byte_count = _content_evidence(question)
        questions.append(
            CodexUserInputQuestionEvidence(
                question_id=question_id,
                content_sha256=content_sha256,
                content_byte_count=content_byte_count,
                option_count=option_count,
                is_other=is_other,
                is_secret=is_secret,
            )
        )

    return CodexUserInputRequestEvidence(
        protocol=protocol,
        request_id=request_id,
        thread_id=thread_id,
        turn_id=turn_id,
        item_id=item_id,
        is_blocking=is_blocking,
        auto_resolution_ms=auto_resolution_ms,
        questions=tuple(questions),
        raw_sha256=hashlib.sha256(raw).hexdigest(),
        raw_byte_count=len(raw),
    )


def _answers_payload(
    request: CodexUserInputRequestEvidence,
    answers: Mapping[str, Sequence[str]],
) -> dict[str, dict[str, list[str]]]:
    if not isinstance(request, CodexUserInputRequestEvidence):
        raise CodexUserInputContractError("request must be validated request evidence")
    _require_exact_protocol(request.protocol)
    if not isinstance(answers, Mapping):
        raise CodexUserInputContractError("answers must be a question-id mapping")
    expected = tuple(question.question_id for question in request.questions)
    if set(answers) != set(expected) or len(answers) != len(expected):
        raise CodexUserInputContractError(
            "response answers must contain every request question id exactly once"
        )
    payload: dict[str, dict[str, list[str]]] = {}
    for question_id in expected:
        raw_answers = answers[question_id]
        if isinstance(raw_answers, (str, bytes)) or not isinstance(raw_answers, Sequence):
            raise CodexUserInputContractError(f"answers[{question_id!r}] must be a sequence")
        if not 1 <= len(raw_answers) <= _MAX_ANSWERS_PER_QUESTION:
            raise CodexUserInputContractError(
                f"answers[{question_id!r}] must contain 1..{_MAX_ANSWERS_PER_QUESTION} answers"
            )
        values = [
            _text(
                answer,
                where=f"answers[{question_id!r}][{index}]",
                max_bytes=_MAX_ANSWER_BYTES,
            )
            for index, answer in enumerate(raw_answers)
        ]
        payload[question_id] = {"answers": values}
    return payload


def build_raw_user_input_response(
    request: CodexUserInputRequestEvidence,
    answers: Mapping[str, Sequence[str]],
    *,
    protocol: CodexUserInputProtocolIdentity,
) -> bytes:
    """Build canonical raw response custody; callers must keep these prose bytes out of evidence."""

    _require_exact_protocol(protocol)
    if not isinstance(request, CodexUserInputRequestEvidence) or request.protocol != protocol:
        raise CodexUserInputContractError("request evidence does not match the protocol identity")
    raw = (
        _canonical_json(
            {"id": request.request_id, "result": {"answers": _answers_payload(request, answers)}}
        )
        + b"\n"
    )
    if len(raw) > _MAX_RAW_BYTES:
        raise CodexUserInputContractError("response raw custody exceeds the bounded size")
    return raw


def validate_raw_user_input_response(
    raw: bytes,
    *,
    request: CodexUserInputRequestEvidence,
    protocol: CodexUserInputProtocolIdentity,
) -> CodexUserInputResponseEvidence:
    """Validate response custody, completeness and correlation without retaining answer prose."""

    _require_exact_protocol(protocol)
    if not isinstance(request, CodexUserInputRequestEvidence) or request.protocol != protocol:
        raise CodexUserInputContractError("request evidence does not match the protocol identity")
    response = _exact(_parse_raw(raw, where="response"), _RESPONSE_FIELDS, "response")
    request_id = _same_request_id(response["id"], request.request_id, "response.id")
    result = _exact(response["result"], _RESULT_FIELDS, "response.result")
    raw_answers = result["answers"]
    if not isinstance(raw_answers, dict):
        raise CodexUserInputContractError("response.result.answers must be an object")
    expected = tuple(question.question_id for question in request.questions)
    if set(raw_answers) != set(expected) or len(raw_answers) != len(expected):
        raise CodexUserInputContractError(
            "response answers must contain every request question id exactly once"
        )

    answers: list[CodexUserInputAnswerEvidence] = []
    for question_id in expected:
        answer = _exact(raw_answers[question_id], _ANSWER_FIELDS, f"answers[{question_id!r}]")
        values = answer["answers"]
        if not isinstance(values, list) or not 1 <= len(values) <= _MAX_ANSWERS_PER_QUESTION:
            raise CodexUserInputContractError(
                f"answers[{question_id!r}].answers must contain "
                f"1..{_MAX_ANSWERS_PER_QUESTION} answers"
            )
        for index, value in enumerate(values):
            _text(
                value,
                where=f"answers[{question_id!r}].answers[{index}]",
                max_bytes=_MAX_ANSWER_BYTES,
            )
        content_sha256, content_byte_count = _content_evidence(values)
        answers.append(
            CodexUserInputAnswerEvidence(
                question_id=question_id,
                content_sha256=content_sha256,
                content_byte_count=content_byte_count,
                answer_count=len(values),
            )
        )

    return CodexUserInputResponseEvidence(
        protocol=protocol,
        request_id=request_id,
        thread_id=request.thread_id,
        turn_id=request.turn_id,
        item_id=request.item_id,
        answers=tuple(answers),
        raw_sha256=hashlib.sha256(raw).hexdigest(),
        raw_byte_count=len(raw),
    )


__all__ = [
    "ADAPTER",
    "EXACT_PROTOCOL_IDENTITY",
    "PARAMS_SCHEMA_SHA256",
    "PARAMS_SCHEMA_TITLE",
    "PROVIDER",
    "PROVIDER_VERSION",
    "REQUEST_METHOD",
    "RESPONSE_SCHEMA_SHA256",
    "RESPONSE_SCHEMA_TITLE",
    "CodexUserInputAnswerEvidence",
    "CodexUserInputContractError",
    "CodexUserInputProtocolIdentity",
    "CodexUserInputQuestionEvidence",
    "CodexUserInputRequestEvidence",
    "CodexUserInputResponseEvidence",
    "build_raw_user_input_response",
    "validate_raw_user_input_request",
    "validate_raw_user_input_response",
]
