#!/usr/bin/env python3
"""Stop coordinator adapter — generated by bear-hug P02. Do not edit by hand.

Thin by design: insert the vendored runtime on the path, hand it the event, write what it
returns. All gate logic lives in scripts/hooks/_bearhug/, where it is tested.

The one policy that lives HERE is what to do when this file itself cannot reach the runtime,
because nothing inside the runtime can decide that.
"""

import json
import os
import sys

#: Copied LITERALLY from scripts/hooks/_bearhug/coordinator.py, not imported: the condition this
#: is needed for is the one where importing the runtime is what failed. bear-hug reads the constant
#: out of the runtime source when generating this file, and a lab test asserts the copies agree.
COORDINATOR_ERROR_REMEDIATION = "The Stop coordinator is misconfigured and cannot evaluate this turn. Roll back the coordinator registration; do not rely on Stop gating until it is restored.\n\nThis is a coordinator fault, not a gate's: no gate result for this turn is trustworthy."


def _fault(exception_type):
    """The bytes this adapter writes when IT is the component that failed.

    Carries the exception TYPE and never its message: a message can hold a path, a command or a
    fragment of source, and this string is shown to the model.
    """
    reason = COORDINATOR_ERROR_REMEDIATION + (
        "\n\nDetail: the Stop coordinator could not be run: " + exception_type
    )
    return json.dumps(
        {"decision": "block", "reason": reason}, ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")


def main(payload):
    # The adapter is installed at <repo>/scripts/hooks/stop-coordinator.py.  Its own location is the
    # git-root fallback stamp.sh obtains with `git rev-parse --show-toplevel`, without depending on
    # the process cwd (which may be a subdirectory) or spawning a command before the runtime loads.
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..")
    )
    sys.path.insert(0, os.path.join(root, "scripts", "hooks"))

    from _bearhug import coordinator
    from _bearhug.readers import (
        board_for, repo_for, tasks_for, transcript_lines_for, transcript_readable_for,
    )

    # Both observability roots supplied EXPLICITLY. The runtime's own defaults resolve to the
    # same places; passing them makes the adapter's docstring claim ("which the adapter supplies")
    # true rather than aspirational, and puts the one line a reader has to check about where
    # telemetry lands in the file they are already reading.
    from _bearhug.telemetry_store import default_root as telemetry_root

    return coordinator.run(payload, dependencies={
        "tasks": tasks_for(payload),
        "repo": repo_for(root),
        "transcript_lines": transcript_lines_for(payload),
        "transcript_readable": transcript_readable_for(payload),
        "board": board_for(root),
    }, stamp_root=root, telemetry_root=telemetry_root(root))


if __name__ == "__main__":
    try:
        event = json.load(sys.stdin)
    except BaseException:  # noqa: BLE001 — D04 rules the INPUT-parse failure FAIL-OPEN
        sys.exit(0)

    try:
        rendered = main(event)
        out, code = rendered.stdout, rendered.exit_code
    except BaseException as exc:  # noqa: BLE001 — the adapter's own fault, ruled fail-closed
        # BaseException, not Exception: a MemoryError or an interrupted Stop hook did not verify
        # this turn either, and `except Exception` is exactly the width that let round 4's defect
        # through one layer down.
        out, code = _fault(type(exc).__name__), 0

    if out:
        sys.stdout.buffer.write(out)
        sys.stdout.buffer.write(b"\n")
    sys.exit(code)
